### ISSUE TITLE
Interested to collaborate and contribute

### ISSUE THREAD

**Issue by rjarun8** [s-aravindh/multiocr#2]
Hi @s-aravindh ,
I would like to contribute towards this package. Shall i pick up a feature or two ?

**Comment by s-aravindh** [comment]
Hello @rjarun8  Thanks for your interest in contributing.
I still haven't prepared or planned for a contributing guide.

can you also let me know which OCR backend you're planning to contribute??

please check [WIP section in readme](https://github.com/s-aravindh/multiocr#wip---ocr-backends) for planned future OCR backend support.
